# Generated by Django 4.2.6 on 2023-10-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='output_photos/')),
                ('percent', models.CharField(max_length=255, null=True)),
                ('fragments', models.FloatField(null=True)),
                ('fragmented_degrades', models.FloatField(null=True)),
                ('normals', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Image Data',
                'verbose_name_plural': 'Image Data',
            },
        ),
    ]
