# Generated by Django 4.2.5 on 2023-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedModel', '0003_alter_imagedata_fragmented_degrades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='img_bytes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='output_photos'),
        ),
    ]
