# Generated by Django 4.2.5 on 2023-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('percent', models.CharField(max_length=255)),
                ('fragments', models.IntegerField()),
                ('fragmented_degrades', models.IntegerField()),
                ('normals', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Image Data',
                'verbose_name_plural': 'Image Data',
            },
        ),
    ]
