# Generated by Django 4.2.5 on 2023-10-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semenModel', '0006_alter_imagedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='output_photos'),
        ),
    ]
